apiVersion: v1
kind: Service
metadata:
  name: minio-svc-lb
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      name: api
      targetPort: 9000
      nodePort: 30900
    - port: 9001
      name: console
      targetPort: 9001
      nodePort: 30901
  selector:
    app: minio
