apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: "cm9vdAo=" # echo root | base64
  MINIO_ROOT_PASSWORD: "TXlNaW5JT1NlY3JldEtleTEyMwo=" # echo MyMinIOSecretKey123 | base64
